name: CodeTour watch

on:
    pull_request:
        types: [opened, edited, synchronize, reopened]

jobs:
    codetour-watch:
        runs-on: ubuntu-latest
        if: github.actor != 'trailheadapps-bot' && github.actor != 'dependabot[bot]'
        steps:
            - name: 'Checkout source code'
              uses: actions/checkout@v4

            - name: 'Watch CodeTour changes'
              uses: pozil/codetour-watch@v3.0.0

    skip-codetour-watch:
        if: github.actor == 'trailheadapps-bot' || github.actor == 'dependabot[bot]'
        runs-on: ubuntu-latest
        steps:
            - name: Noop
              run: |
                  echo "Skipping workflow run for automated PRs."
