# Unique name for this workflow
name: Develop MetaData Deploy

# Definition when the workflow should run
on:
    workflow_dispatch:
    push:
        branches:
            - develop
        paths:
            - force-app/**'
jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate on develop
        uses: jawills/sf-deploy@v1.0
        with:
          SFDX_AUTH_URL: ${{ secrets.DEVHUB_SFDX_URL }}
          DRY_RUN: false