# Unique name for this workflow
name: metadata deploy on production environment

# Workflow starts when receiving custom event sent by CI workflow
on:
    workflow_dispatch:
    push:
        branches:
            - main

# Jobs to be executed
jobs:
    prod-sandbox:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: jawills/sf-deploy@v1.0
              with:
                  SFDX_AUTH_URL: ${{ secrets.DEVHUB_SFDX_URL }}
                  DRY_RUN: false
